### ISSUE TITLE
Alice Signing Secret

### ISSUE THREAD

**Issue by jMyles** [nucypher/taco-web#162]
Most of Alice's signatures seem to be transactions, the secret of which is of course contained in the wallet.

However, we have the nagging problem of how Alice's payment (to the Cohort) becomes authorized for use by a particular Enrico (or perhaps, in some scenario, where the Conditions adhered are themselves bound to rules set by Alice).

Does Alice need a separate Signing Secret for this purpose?

In a label-derivation scheme, as @KPrasch has occasionally mused, presumably the material used for the derivation is signed such that not only Enrico, but Bob can ultimately verify the signature (for example, to prove that he acquired it via a legitimate adjudication of the conditions, rather than via a leak).

**Comment by arjunhassard** [comment]
Covered by https://github.com/nucypher/tdec/issues/145
