### ISSUE TITLE
Add an ability to specify a node version in `Cohort`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/taco-web#170]
- User adds a `version` field to the `Cohort` object to select a group of nodes that satisfy certain node version
- Porter must expose another query parameter in `/get_ursulas`: `version`
- `version` structure should follow semver, or whichever scheme we use to denote node version

**Comment by arjunhassard** [comment]
This becomes much more of a problem when a given app is creating lots of cohorts on the fly, whereas for early versions they're unlikely to have more than a single semi-perpetual cohort. On the staker side, we can assume a level of professionalism (given the smaller group) and sampling/incentive mitigations to make sure all nodes are on the latest version

**Comment by derekpierre** [comment]
Will be addressed as part of https://github.com/nucypher/taco-web/issues/264
