### ISSUE TITLE
Source ritual validator public keys from `Coordinator` contract

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/taco-web#234]
- Downstream of changes in https://github.com/nucypher/nucypher-contracts/pull/77
- Related: https://github.com/nucypher/nucypher/pull/3188

**Comment by derekpierre** [comment]
@piotr-roslaniec closing this issue. Seems like this has already been addressed for TACo launch i.e. v7.0.0. Not sure if there was a `taco-web` associated issue.

Original work done to move away from P2P for validator public key and instead use contract. https://github.com/nucypher/nucypher/pull/3213.
