### ISSUE TITLE
Before initializing a ritual, ensure that `Cohort` participants meet staking requirements 

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/taco-web#235]
- Currently, it's possible to construct a `Cohort` that doesn't meet CBD staking requirements
- Integrate with the `StakeInfo` contract and validate participants against staking requirements before initializing a ritual
- Blocked by https://github.com/nucypher/nucypher-ts/issues/264

**Comment by derekpierre** [comment]
This seems more like a Porter sampling issue.
