### ISSUE TITLE
Error: Could not convert input for treasure_map to a TreasureMap: Failed to deserialize: differing major version: expected 3, got 1

### ISSUE THREAD

**Issue by singhvivek2503** [nucypher/taco-web#237]
I am getting below error when trying to decrypt a message:
>"Could not convert input for treasure_map to a TreasureMap: Failed to deserialize: differing major version: expected 3, got 1"

Below is the code snippet:

            const depStrategy = strategy as DeployedStrategy;
            const web3Provider = new providers.Web3Provider(window.ethereum);
            const decrypter = depStrategy.decrypter;
    
            const conditionContext = conditionSet.buildContext(web3Provider);
            const retrievedMessages = await decrypter.retrieve(
                [encryptedPrivateKey],
                conditionContext
            ); 

nucyper-ts version is "@nucypher/nucypher-ts": "^0.9.0".

It was working fine util few days back but now it is not. Please guide. Thanks.

**Comment by KPrasch** [comment]
Thanks for the issue!  This is caused by a recent update to the version of nucypher running on the `tapir` testnet.  You may need to update your dependencies to use the latest released version of nucypher-ts, however, we will be posting migration instructions in the official documentation soon.

**Comment by piotr-roslaniec** [comment]
`nucypher-ts@0.9.0` has been deprecated. Please see the [package tags on npmjs.com](https://www.npmjs.com/package/@nucypher/nucypher-ts?activeTab=versions) to find compatible `nucypher-ts` version and test networks:

![image](https://github.com/nucypher/nucypher-ts/assets/39299780/9ff3de33-e10c-40ec-8a57-f7f7bb030627)

**Comment by singhvivek2503** [comment]
@KPrasch Thanks for your response. When can we accept the migration guide? I am struggling to upgrade to newer version.

**Comment by KPrasch** [comment]
> @KPrasch Thanks for your response. When can we accept the migration guide? I am struggling to upgrade to newer version.

Your feedback is useful here, what issues are you encountering? Do you plan to use CBD or PRE?

**Comment by singhvivek2503** [comment]
> > @KPrasch Thanks for your response. When can we accept the migration guide? I am struggling to upgrade to newer version.
> 
> Your feedback is useful here, what issues are you encountering? Do you plan to use CBD or PRE?

I am using CBD. Issue is cannot find some of the previously imported members after the upgrade.
<img width="795" alt="Screenshot 2023-07-06 at 9 19 16 PM" src="https://github.com/nucypher/nucypher-ts/assets/17641164/fb3b1a69-414e-4b11-a65d-3b242660c850">

**Comment by singhvivek2503** [comment]
> https://porter.nucypher.io/

After uri change to mainnet. It gives error:
> Could not convert input for retrieval_kits to a valid checksum address: Failed to deserialize: unsupported minor version: expected <=0,got 1

**Comment by KPrasch** [comment]
> @piotr-roslaniec After uri change to mainnet. It gives error:
> 
> > Could not convert input for retrieval_kits to a valid checksum address: Failed to deserialize: unsupported minor version: expected <=0,got 1

Please ensure that you are using the verison of nucypher-ts that is tagged `mainnet` for use on etheruem mainnet.

**Comment by singhvivek2503** [comment]
> > @piotr-roslaniec After uri change to mainnet. It gives error:
> > > Could not convert input for retrieval_kits to a valid checksum address: Failed to deserialize: unsupported minor version: expected <=0,got 1
> 
> Please ensure that you are using the version of nucypher-ts that is tagged `mainnet` for use on etheruem mainnet.

I upgraded to version `1.0.0-beta.1` (tapir) and related code but now I get another error:
> Number of provided requests must be >= the expected threshold

The threshold is 3 but only 2 `encrypted_decryption_requests` are being sent in the payload. What am I missing here?

**Comment by piotr-roslaniec** [comment]
@singhvivek2503 What is the content of your `Cohort`? Perhaps there are not enough available validators on `tapir`.

**Comment by singhvivek2503** [comment]
> @singhvivek2503 What is the content of your `Cohort`? Perhaps there are not enough available validators on `tapir`.
> 
> Edit: There are enough validators on `tapir`, but the DKG ritual currently used in the SDK is limited to 2 validators. So setting `shares` to 2 should fix your issue. This limitation will be removed after this PR is merged: #233

I reduced shares and threshold both to 2. Now I get error `500`:
> After 10 seconds and 88 rounds, didn't find these 2 nodes: {'0xb15d5A4e2be34f4bE154A1b08a94Ab920FfD8A41', '0x210eeAC07542F815ebB6FD6689637D8cA2689392'}

**Comment by piotr-roslaniec** [comment]
@singhvivek2503 I reproduced that error. Looks like one of the nodes may be down. Let me get back to you when we fix that.

**Comment by derekpierre** [comment]
Assume this is now resolved.

Also CBD is now TACo and uses the `@nucypher/taco` library.
