### ISSUE TITLE
Handle ritual initialization timeout

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/taco-web#249]
- When initializing the ritual, handle a case where ritual participants may not contribute in a timely manner
- Check [ritual timeout](https://github.com/nucypher/nucypher-contracts/blob/main/contracts/contracts/coordination/Coordinator.sol#L76-L77) when waiting for `EndRitual` event

**Comment by derekpierre** [comment]
Let's handle this as part of #264 , if we go down that route.
