### ISSUE TITLE
Missing peer dependency `@nucypher/core`

### ISSUE THREAD

**Issue by ghardin1314** [nucypher/taco-web#401]
Getting this warning when installing `"@nucypher/taco": "0.1.0-rc.6"`. I think potentially an issue with how the packages are configured in the monorepo

```bash
packages/api/core
└─┬ @nucypher/taco 0.1.0-rc.6
  └── ✕ missing peer @nucypher/shared@"*"
Peer dependencies that should be installed:
  @nucypher/shared@"*" 
  ```

**Comment by ghardin1314** [comment]
Confirmed working with `0.1.0-rc.4`, 

`rc.5` also broken

**Comment by piotr-roslaniec** [comment]
Hi, and thanks for reporting this issue.

`pnpm` is going to fail on missing peer deps by default, other package managers are more lenient. Nevertheless, there is room for improvement.
