### ISSUE TITLE
Update code example readmes

### ISSUE THREAD

**Issue by manumonti** [nucypher/taco-web#413]
From EthIstambul hacker's feedback:

- Some complaints about code examples in the repo are not fully synced with the documentation in docs.threshold.network.

- Some readmes in examples still have deprecated information from pre-monorepo era.

**Comment by manumonti** [comment]
Closed since I moved this feedback to https://github.com/nucypher/tdec/issues/139

**Comment by piotr-roslaniec** [comment]
@manumonti I think we can close this one
