### ISSUE TITLE
Syntactic validation of JSONPath queries while creating conditions

### ISSUE THREAD

**Issue by KPrasch** [nucypher/taco-web#559]
Originally identified here https://github.com/nucypher/taco-web/pull/550/files#r1696888086

**Comment by derekpierre** [comment]
zod.refine and a jsonpath library will be your friend.

Analogous to the SIWE message string validation - https://github.com/nucypher/taco-web/blob/main/packages/taco-auth/src/providers/eip4361.ts#L20, https://github.com/nucypher/taco-web/blob/main/packages/taco-auth/src/providers/eip4361.ts#L9

**Comment by KPrasch** [comment]
After some experimentation it appears that the grammar parsing of jsonpath-plus does not enforce syntactically invalid expressions.  In fact there is a section from the official documentation mentioning this:

> Grammar
This project uses a formal BNF [grammar](https://github.com/dchester/jsonpath/blob/master/lib/grammar.js) to parse JSONPath expressions, an attempt at reverse-engineering the intent of the original implementation, which parses via a series of creative regular expressions. The original regex approach can sometimes be forgiving for better or for worse (e.g., $['store] => $['store']), and in other cases, can be just plain wrong (e.g. [ => $).

Even the expression `...store..  ..book[****` is parsed (incorrectly) into the array `Array(8) ["", .., store, .., "", .., book, ****]`

Ultimately this is both a developer experience (early error detection/prevention) and a compatibility concern (syntactically invalid expressions will not be rejected by taco nodes).

**Comment by derekpierre** [comment]
Closed via #561
